---
- name: "[PRE-TASK] Fetch config.xml from remote host"
  ansible.builtin.fetch:
    src: "{{ config_file }}"
    dest: "{{ local_file }}"
    flat: true

- name: Set System Theme
  delegate_to: localhost
  notify: Upload config
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}"
    value: "{{ opnsense_theme_name }}"

- name: Install Theme Packages
  community.general.pkgng:
    name: "{{ opnsense_theme_package }}"
    state: present
  when: opnsense_theme_package is defined

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
